[package]
name = "web-server"
version = "0.1.0"
authors = ["Chris Lane <chrisl@cube19.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
